---
####################
# Python Bootstrap #
####################

# Check if Python is installed, and its version. If Python isn't installed, or it's at a version below 2.7.9, install Python 2.7.9.
# Currently only for CentOS6. See: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1877

- name: Check for Python 2's version
  shell: python -V 2>&1 | grep -Po '(?<=Python )(.+)'
  register: python_version
  ignore_errors: yes
  when:
    - (ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6")
  tags: 
    - python2.7

- name: Yum install prerequisites to build Python 2.7.9
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - xz-libs
    - wget
  when: 
    - (ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6")
    - (python_version.rc != 0) or (python_version.rc == 0 and python_version.stdout is version_compare('2.7.9', operator='lt') )
  tags:
    - python2.7

- name: Download & extract Python 2.7.9 source
  unarchive: 
    src: http://www.python.org/ftp/python/2.7.9/Python-2.7.9.tar.xz 
    dest: /tmp/
    remote_src: yes
    mode: 0755
  retries: 3 
  delay: 5
  register: python_download
  until: python_download is not failed
  when: 
    - (ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6")
    - (python_version.rc != 0) or (python_version.rc == 0 and python_version.stdout is version_compare('2.7.9', operator='lt') )
  tags:
    - python2.7

- name: Configure, build & make/make altinstall
  shell: |
    cd /tmp/Python-2.7.9 && ./configure --prefix=/usr/local && make && make altinstall
  when:
    - (ansible_distribution == "CentOS") and (ansible_distribution_major_version == "6")
    - (python_version.rc != 0) or (python_version.rc == 0 and python_version.stdout is version_compare('2.7.9', operator='lt') )
  tags:
    - python2.7
