---
##############################
# Enable IPv6 in sysctl.conf #
##############################

- name: Setting net.ipv6.conf.all.disable_ipv6 = 0
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '0'
    sysctl_set: yes
    state: present
    reload: no
  when:
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")
  tags:
    - IPv6_sysctl
    - adoptopenjdk

- name: Setting net.ipv6.conf.default.disable_ipv6 = 0
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
  when:
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")
  tags:
    - IPv6_sysctl
    - adoptopenjdk
