---
########
# CPAN #
########

# Additional steps for RedHat and SLES
- name: Install cpanminus RedHat 6, CentOS 6 and SLES
  shell: "curl -L https://cpanmin.us | perl - App::cpanminus"
  ignore_errors: yes
  when:
    - (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")
    - (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
    - ansible_distribution == "SLES"
    - ansible_distribution == "MacOSX"
  tags:
    - cpan
    - test_tools
    - skip_ansible_lint
    #TODO: curl used in place of get_url or uri module

- name: Install cpanminus RedHat 7 and Centos 7
  yum:
    name: cpanminus
    state: installed
  when:
    - (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7") or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  tags:
    - cpan
    - test_tools

# All
- name: Install JSON
  command: cpanm --with-recommends --sudo JSON
  tags:
    - cpan
    - json
    # TODO: write a condition when NOT to run this step
    - skip_ansible_lint

- name: Install Text::CSV
  command: cpanm --with-recommends --sudo Text::CSV
  tags:
    - cpan
    - text_csv
    # TODO: write a condition when NOT to run this step
    - skip_ansible_lint

- name: Install XML::Parser
  command: cpanm --with-recommends --sudo XML::Parser
  tags:
    - cpan
    - xml_parser
    # TODO: write a condition when NOT to run this step
    - skip_ansible_lint
