---
arch:
  - amd64
  - arm64-graviton2
  - ppc64le

env:
  - TARGET="adoptopenjdk/centos7_build_image"

os:
  - linux

dist: bionic

virt: lxd
group: edge
install: skip

script:
  - docker build -t $TARGET:$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH -f ansible/Dockerfile.CentOS7 .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push $TARGET:$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH; fi

jobs:
  include:
    - stage: manifest
      script: export DOCKER_CLI_EXPERIMENTAL=enabled &&
        AMD64=$TARGET:linux-amd64 &&
        ARM64=$TARGET:linux-arm64 &&
        PPC64LE=$TARGET:linux-ppc64le &&
        docker manifest create adoptopenjdk/centos7_build_image $AMD64 $ARM64 $PPC64LE &&
        docker manifest annotate $TARGET $AMD64 --arch amd64 --os linux &&
        docker manifest annotate $TARGET $ARM64 --arch arm64 --os linux &&
        docker manifest annotate $TARGET $PPC64LE --arch ppc64le --os linux
      after_success:
        - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker manifest push $TARGET; fi
