---
# tasks file for Nagios_Installation

- name: Include distribution variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Run Nagios-Core Installation
  include_tasks: install_nagios_core.yml
  when: '"install_core" in task_list'

- name: Run Nagios-Plugins installation
  include_tasks: install_nagios_plugins.yml
  when: '"install_plugins" in task_list'

- name: Run PNP$NAGIOS-Plugin installation
  include_tasks: install_pnp4nagios.yml
  when: '"install_pnp4nagios" in task_list'

- name: Run install_nagiosgraph installation
  include_tasks: install_nagiosgraph.yml
  when: '"install_nagiosgraph" in task_list'

- name: Copy Additional Nagios Scripts
  include_tasks: install_nagios_scripts.yml
  when: '"install_nagios_scripts" in task_list'

- name: Configure Nagios-Core
  include_tasks: configure_nagios_core.yml
  when: '"configure_nagios_core" in task_list'

- name: Configure Nagios-Commands
  include_tasks: configure_nagios_commands.yml
  when: '"configure_nagios_commands" in task_list'
