---
##########################
# adoptopenjdk_variables #
##########################

# Domain for setting hostname
Domain: adoptopenjdk.net

# Sudoers file
Sudoers_File: /etc/sudoers

# Jenkins User Variables:
Jenkins_Username: jenkins

# Superuser Variables:
Superuser_Account: Enabled

# Nagios Variables:
Nagios_Plugins: Enabled
Nagios_Monitoring: Enabled
Nagios_Master_IP: 78.47.239.96

# Security Variables:
Security: Enabled

# JCK Variables:
jckftp_Username: jckftp

# Vendor Variables:
Vendor_File: Disabled
Vendor_Playbook: /Vendor_Files/Vendor_Playbook/Vendor.yml

# Default BootJDK installed
bootjdk: hotspot

# Version of Ant used
ant_version: 1.10.15
ant_checksum: sha512:1de7facbc9874fa4e5a2f045d5c659f64e0b89318c1dbc8acc6aae4595c4ffaf90a7b1ffb57f958dd08d6e086d3fff07aa90e50c77342a0aa5c9b4c36bff03a9

# GPG Public Keys
key:
  curl: 27EDEAF22F3ABCEB50DB9A125CC908FDB71E12C2 # Daniel Stenberg <daniel@haxx.se>
  apache_ant: 0A123C1ED3F13A6A0140E166C71FB765CD9DE313 # Jaikiran Pai <jaikiran@apache.org>
  apache_maven: B02137D875D833D9B23392ECAE5A7FB608A0221C # Robert Scholte <rfscholte@apache.org>
  autoconf: A7A16B4A2527436A # Eric Blake <eblake@redhat.com>
  cmake: EC8FEF3A7BFB4EDA # Brad King <brad.king@kitware.com>
  gmake: 96B047156338B6D4 # Paul Smith (Mad Scientist) <psmith@gnu.org>
  adoptium: 3B04D753C9050D9A5D343F39843C48A565F8F04B # Adoptium GPG Key (DEB/RPM Signing Key) <temurin-dev@eclipse.org>
