---
###################
# Strawberry Perl #
###################

- name: Test if Strawberry Perl is already installed
  win_stat:
    path: 'C:\Strawberry\perl'
  register: strawberry_perl_installed
  tags: Strawberry_Perl

- name: Check if Strawberry Perl is already downloaded
  win_stat:
    path: 'C:\temp\strawberry-perl.zip'
  register: strawberry_perl_download
  tags: Strawberry_Perl

- name: Download Strawberry Perl
  win_get_url:
    url: http://strawberryperl.com/download/5.26.0.1/strawberry-perl-5.26.0.1-64bit.zip
    dest: C:\temp\strawberry-perl.zip
    checksum: 0f89ce99be64679f930e9cca25ccec09de8aff2fc5db3c0dd4158d9606532ad5
    checksum_algorithm: sha256
  when: (not strawberry_perl_download.stat.exists) and (not strawberry_perl_installed.stat.exists)
  tags: Strawberry_Perl

- name: Unzip Strawberry Perl
  win_unzip:
    src: C:\temp\strawberry-perl.zip
    dest: C:\Strawberry
  when: (not strawberry_perl_installed.stat.exists)
  tags: Strawberry_Perl

- name: Add Strawberry Perl to %PATH%
  win_path:
    elements:
      - 'C:\Strawberry\perl\bin'
    state: present
  when: (not strawberry_perl_installed.stat.exists)
  tags: Strawberry_Perl

- name: Install Text::CSV_XS
  win_command: C:\Strawberry\perl\bin\perl -MCPAN -e "install Text::CSV_XS"
  when: (not strawberry_perl_installed.stat.exists)
  tags: Strawberry_Perl

- name: Clean up strawberry-perl.zip
  win_file:
    path: C:\temp\strawberry-perl.zip
    state: absent
  tags: Strawberry_Perl
