---
###############
# OracleLinux #
###############

# Workaround fix to Pi's clock skew, date and time reset issue: Jan 1 1970
- name: Get Ansible Host's data and time
  set_fact:
    date_time: "{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"
  tags: time_fix

- name: Set date and time
  shell: date "+%Y-%m-%d %H:%M" -s " {{ date_time }} "
  tags: time_fix

#########################################
# Configure Repos and Update the system #
#########################################
- name: Add Oracle Linux 7 repository
  yum_repository:
    name: ol7_el7
    description: Oracle Linux 7 (aarch64) Latest
    baseurl: http://yum.oracle.com/repo/OracleLinux/OL7/latest/aarch64/
    gpgcheck: no
    enabled: yes

- name: YUM upgrade all packages
  yum:
    name: '*'
    state: latest
  tags: patch_update

############################
# Build Packages and tools #
############################
- name: Call Build Packages and Tools Task
  include_tasks: build_packages_and_tools.yml

#########
# expat #
#########
- name: Install expat
  get_url:
    url: https://github.com/libexpat/libexpat/releases/download/R_2_2_5/expat-2.2.5.tar.bz2
    dest: /tmp/
    mode: 0440
    timeout: 25
    validate_certs: no
  tags: expat

- name: Extract expat
  unarchive:
    src: /tmp/expat-2.2.5.tar.bz2
    dest: /tmp/
    copy: False
  tags: expat

- name: Running ./configure & make for expat
  shell: cd /tmp/expat-2.2.5 && ./configure && make -j {{ ansible_processor_vcpus }} && sudo make install
  become: yes
  tags: expat
