---
##########################
# adoptopenjdk_variables #
##########################

# Jenkins User Variables:
Jenkins_Username: jenkins
Jenkins_User_SSHKey: /Vendor_Files/keys/id_rsa.pub

# Superuser Variables:
Superuser_Account: Enabled
Zeus_User_SSHKey: /Vendor_Files/keys/zeus.key

# Nagios Variables:
Nagios_Plugins: Enabled
Nagios_User_SSHKey: /Vendor_Files/keys/nagios.key
Nagios_Monitoring: Enabled
Nagios_Master_IP: 78.47.239.96

# Security Variables:
Security: Enabled
Keybox_SSHKey: /Vendor_Files/keys/keybox.key

# JCK Variables:
jckftp_Username: jckftp
jckftp_Passwd: /Vendor_Files/passwords/ftp

# Vendor Variables:
Vendor_File: Disabled
Vendor_Playbook: /Vendor_Files/Vendor_Playbook/Vendor.yml
