###################
# IBM XL C 13.1.3 #
###################
---
- name: Checking for XLC13 availability
  stat:
    path: /usr/lpp/xlCcmp.13.1.3
  register: xlc13
  tags: xlc13

- name: Unpack and install Vendor Files
  when: xlc13.stat.isdir is undefined
  tags: [xlc13, vendor_files]
  block:
    - name: Transfer and Extract XLC13
      unarchive:
        src: /Vendor_Files/aix/XLC/IBM_XL_C_C___FOR_AIX_V13.1.3_EMG.tar.gz
        dest: /tmp
        remote_src: false
      failed_when: false
      register: _vendor_copied

    - name: Install IBM XLC13 - installp
      command: installp -aXYg -e /tmp/usr/install.log -d /tmp/usr/sys/inst.images all
      register: _installp
      failed_when: false
      when: _vendor_copied.failed != true

    - name: Remind that installp error messages may be ignored
      debug:
        msg='Errors from the previous installp command normal'
      when: _installp.skipped is not defined

    - name: Clean XLC13 tmp files
      file:
        path: /tmp/usr
        state: absent

- name: TestIBM XLC13
  command: /opt/IBM/xlC/13.1.3/bin/xlc -qversion
  register: xlc13_qversion
  failed_when: false
  changed_when: false
  tags: xlc13

- name: Display XLC13 qversion information
  debug:
    msg: "{{ xlc13_qversion.stdout }}"
  when: xlc13_qversion.failed == false
  changed_when: false
  tags: xlc13

- name: Inform about XLC13 not found
  debug:
    msg: "{{ xlc13_qversion.cmd }} returns: {{ xlc13_qversion.msg }}"
  when: xlc13_qversion.failed == true
  tags: xlc13
