---
###################################################
# OpenSSL v1.0.2r for building OpenJ9 on CentOS 6 #
###################################################

- name: Test if OpenSSL v1.0.2r is installed
  shell: set -o pipefail | export LD_LIBRARY_PATH=/usr/local/openssl-1.0.2/lib &&  /usr/local/openssl-1.0.2/bin/openssl version | awk '{print $2}' | cut -c 1-5
  when:
    - (ansible_distribution_major_version == "6" and (ansible_distribution == "RedHat" or ansible_distribution == "CentOS") or ansible_distribution == "Debian" or ansible_distribution == "openSUSE")
  register: openssl_version
  tags: openssl

- name: Download OpenSSL v1.0.2r
  get_url:
    url: https://www.openssl.org/source/openssl-1.0.2r.tar.gz
    dest: /tmp/openssl-1.0.2r.tar.gz
    force: no
    mode: 0755
    validate_certs: no
    checksum: sha256:ae51d08bba8a83958e894946f15303ff894d75c2b8bbd44a852b64e3fe11d0d6
  when:
    - (ansible_distribution_major_version == "6" and (ansible_distribution == "RedHat" or ansible_distribution == "CentOS") or ansible_distribution == "Debian" or ansible_distribution == "openSUSE")
    - ((not openssl_version.stdout) or ((openssl_version.stdout) and (openssl_version.stdout is version_compare('1.0.2', operator='lt', strict=True))))
  tags: openssl

- name: Extract OpenSSL v1.0.2r
  unarchive:
    src: /tmp/openssl-1.0.2r.tar.gz
    dest: /tmp
    copy: False
  when:
    - (ansible_distribution_major_version == "6" and (ansible_distribution == "RedHat" or ansible_distribution == "CentOS") or ansible_distribution == "Debian" or ansible_distribution == "openSUSE")
    - ((not openssl_version.stdout) or ((openssl_version.stdout) and (openssl_version.stdout is version_compare('1.0.2', operator='lt', strict=True))))
  tags: openssl

- name: Build and install OpenSSL v1.0.2r
  shell: cd /tmp/openssl-1.0.2r && ./config --prefix=/usr/local/openssl-1.0.2 shared && make && make install
  when:
    - (ansible_distribution_major_version == "6" and (ansible_distribution == "RedHat" or ansible_distribution == "CentOS") or ansible_distribution == "Debian" or ansible_distribution == "openSUSE")
    - ((not openssl_version.stdout) or ((openssl_version.stdout) and (openssl_version.stdout is version_compare('1.0.2', operator='lt', strict=True))))
  tags: openssl

- name: Remove downloaded packages for OpenSSL v1.0.2r
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/openssl-1.0.2r.tar.gz
    - /tmp/openssl-1.0.2r
  ignore_errors: yes
  when:
    - (ansible_distribution_major_version == "6" and (ansible_distribution == "RedHat" or ansible_distribution == "CentOS") or ansible_distribution == "Debian" or ansible_distribution == "openSUSE")
    - ((not openssl_version.stdout) or ((openssl_version.stdout) and (openssl_version.stdout is version_compare('1.0.2', operator='lt', strict=True))))
  tags: openssl
