---
#########################################################################################
# AdoptOpenJDK - Ansible Playbook to install Nagios plugins on CentOS 7 on x86 hardware #
#########################################################################################

###############
# Nagios user #
###############
- name: Allow Nagios to use yum while restricting it to check-update only
  shell: |
    echo "nagios ALL = NOPASSWD: /usr/bin/yum --security check-update" >> /etc/sudoers
  when:
    - ansible_architecture == "x86_64"

###################
# Install plugins #
###################
- name: Install nagios-plugins-all
  yum:
    name: nagios-plugins-all
    state: latest

##########
# Layout #
##########
- name: Creates Nagios folder
  file: path=/usr/local/nagios/ state=directory mode=0755 owner=nagios

- name: Create symlink to plugins
  file: src=/usr/lib64/nagios/plugins dest=/usr/local/nagios/libexec state=link

##############################
# Install additional plugins #
##############################
- name: Copy check_yum plugin
  copy:
    src: roles/Nagios_Plugins/tasks/additional_plugins/check_yum
    dest: /usr/local/nagios/libexec/check_yum
    mode: 0755

- name: Copy check_ntp_timesync plugin
  copy:
    src: roles/Nagios_Plugins/tasks/additional_plugins/check_ntp_timesync
    dest: /usr/local/nagios/libexec/check_ntp_timesync
    mode: 0755
