---
#########################################################################################
# AdoptOpenJDK - Ansible Playbook to install Nagios plugins on CentOS 7 on x86 hardware #
#########################################################################################

###############
# Nagios user #
###############
# Skipping linting as no situation where this can't run (lint error 301)
- name: Allow Nagios to use pkg while restricting it to audit only
  shell: |
    echo "nagios ALL = NOPASSWD: /usr/sbin/pkg audit -F" >> /etc/sudoers

# Skipping linting as no situation where this can't run (lint error 301)
- name: Allow Nagios to use pkg while restricting it to upgrade --dry-run only
  shell: |
    echo "nagios ALL = NOPASSWD: /usr/sbin/pkg upgrade --dry-run" >> /etc/sudoers

###################
# Install plugins #
###################
- name: Download nagios-plugins
  get_url:
    url: https://nagios-plugins.org/download/nagios-plugins-2.2.1.tar.gz
    dest: /tmp/
    mode: 0440
    timeout: 25
    checksum: sha256:647c0ba4583d891c965fc29b77c4ccfeccc21f409fdf259cb8af52cb39c21e18

- name: Extract nagios-plugins
  unarchive:
    src: /tmp/nagios-plugins-2.2.1.tar.gz
    dest: /tmp/
    copy: False

# Skipping linting as no situation where this can't run (lint error 301)
- name: Configure, make and make install nagios-plugins
  shell: cd /tmp/nagios-plugins-2.2.1/ && ./configure --prefix=/usr/local/nagios && make -j {{ ansible_processor_vcpus | default(1) }} && make install
  become: yes

##############################
# Install additional plugins #
##############################
- name: Copy check_pkg plugin
  copy:
    src: roles/Nagios_Plugins/tasks/additional_plugins/check_pkg
    dest: /usr/local/nagios/libexec/check_pkg
    mode: 0755
