---
###############
# IcedTea-Web #
###############

- name: Check if IcedTea-Web 1.8.2 is already downloaded
  win_stat:
    path: 'C:\temp\icedteaWEB182.msi'
  register: icedteaweb_download
  tags: IcedTea-Web

- name: Check if IcedTea-Web 1.8.2 is already installed
  win_stat:
    path: 'C:\Program Files\IcedTeaWEB'
  register: icedteaweb_install
  tags: IcedTea-Web

- name: Download IcedTea-Web 1.8.2
  win_get_url:
    url: https://github.com/AdoptOpenJDK/IcedTea-Web/releases/download/icedtea-web-1.8.2/icedtea-web-1.8.2.msi
    dest: 'C:\temp\icedteaWEB182.msi'
    checksum: 7887693462e357e9ea20901066f9cf015e8fd1b47f9eec9d075a5fd155de27ca
    checksum_algorithm: sha256
  when: (not icedteaweb_download.stat.exists) and (not icedteaweb_install.stat.exists)
  tags: IcedTea-Web

- name: Install IcedTea-Web 1.8.2
  win_package:
    path: 'C:\temp\icedteaWEB182.msi'
    creates_path: 'C:\Program Files\IcedTeaWeb\WebStart\bin\javaws.exe'
    state: present
    arguments: /l* C:\temp\icedteaweb.log /quiet INSTALLDIR="C:\Program Files\IcedTeaWEB"
  when: (not icedteaweb_install.stat.exists)
  tags: IcedTea-Web
