---
###########################
# Apache ANT Installation #
###########################

- name: Test if Ant is already installed
  win_stat:
    path: 'C:\apache-ant\apache-ant-1.10.3'
  register: ant_installed
  tags: ANT

- name: Test if Ant is already downloaded
  win_stat:
    path: 'c:\temp\ant.zip'
  register: ant_download
  tags: ANT

- name: Download Apache ANT
  win_get_url:
    url: http://apache.forsale.plus/ant/binaries/apache-ant-1.10.3-bin.zip
    dest: c:\temp\ant.zip
    force: no
  when: (ant_installed.stat.exists == false) and (ant_download.stat.exists == false)
  register: ant_download
  tags: ANT

- name: Deploy Apache ANT
  win_unzip:
    src: c:\temp\ant.zip
    dest: c:\apache-ant\
    creates: c:\apache-ant
  when: (ant_installed.stat.exists == false)
  tags: ANT

- name: Set ANT_HOME
  raw: setx ANT_HOME "C:\apache-ant\apache-ant-1.10.3"
  when: (ant_installed.stat.exists == false)
  tags: ANT

- name: Add %ANT_HOME%\bin to %PATH%
  win_path:
    elements:
      - '%ANT_HOME%\bin'
    state: present
  when: (ant_installed.stat.exists == false)
  tags: ANT

- name: Test if ant-contrib is already installed
  win_stat:
    path: 'C:\apache-ant\apache-ant-1.10.3\lib\ant-contrib.jar'
  register: ant_contrib_installed
  tags: ANT

- name: Download ant-contrib
  win_get_url:
    url: https://sourceforge.net/projects/ant-contrib/files/ant-contrib/ant-contrib-1.0b2/ant-contrib-1.0b2-bin.zip
    dest: c:\temp\ant-contrib.zip
    force: no
  when: (ant_contrib_installed.stat.exists == false)
  tags: ANT

- name: unzip ant-contrib
  win_unzip:
    src: c:\temp\ant-contrib.zip
    dest: c:\temp\ant-contrib
    creates: c:\temp\ant-contrib
  when: (ant_contrib_installed.stat.exists == false)
  tags: ANT

- name: Copy the ant-contrib.jar to ANT's lib folder
  win_copy:
    src: C:\temp\ant-contrib\ant-contrib\lib\ant-contrib.jar
    dest: C:\apache-ant\apache-ant-1.10.3\lib\ant-contrib.jar
    remote_src: True
  when: (ant_contrib_installed.stat.exists == false)
  tags: ANT
