---
########################################
# AdoptOpenJDK - Ansible Playbook for: #
# -------- Windows 7, 8, 10 ---------  #
# - Windows Server 2008, 2012, 2016  - #
########################################

################
# Please Note: #
################
# *** This playbook assumes that the Windows client machine has been configure to allow Ansible to run on it (WINRM)***
# Ensure you have opened Internet Explorer and completed the setup (other wise wget will not work)
# Run powershell as the Administrator
# wget https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 -OutFile .\ConfigureRemotingForAnsible.ps1
# .\ConfigureRemotingForAnsible.ps1 -CertValidityDays 9999
# .\ConfigureRemotingForAnsible.ps1 -EnableCredSSP
# .\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert
# .\ConfigureRemotingForAnsible.ps1 -SkipNetworkProfileCheck

- hosts: "{{ groups['Vendor_groups'] | default('build*win*:test*win*') }}"
  gather_facts: yes
  tasks:
    - block:
      # Set standard variables
        - name: Load AdoptOpenJDKs variable file
          include_vars: group_vars/all/adoptopenjdk_variables.yml

  #########
  # Roles #
  #########
  roles:
    - Debug
    - Version
    - Common
    - Windows_Updates
    - Jenkins                     # AdoptOpenJDK infrastructure
    - MSVS_2010
    - VS2010_SP1
    - cygwin
    - Firefox
    - Strawberry_Perl             # Testing
    - Freemarker                  # OpenJ9
    - cmake                       # OpenJ9
    - GIT
    - Java7                       # JDK8 build bootstrap
    - Java8                       # JDK9 build bootstrap/ For Gradle
    - role: Java_install          # JDK11 build bootstrap
      jdk_version: 10
    - role: Java_install          # JDK13 build bootstrap
      jdk_version: 12
    - role: Java_install          # JDK14 build bootstrap
      jdk_version: 13
    - ANT                         # Testing
    - MSVS_2013
    - MSVS_2017                   # OpenJ9
    - NVidia_Cuda_Toolkit         # OpenJ9
    - NTP_TIME
    - 7-Zip                       # Mostly extracting other prereqs :-)
    - Clang_64bit                 # OpenJ9
    - Clang_32bit                 # OpenJ9
    - OpenSSL                     # OpenJ9
    - nasm                        # OpenJ9
    - Rust                        # IcedTea-Web
    - IcedTea-Web                 # For Jenkins webstart
