---

#
# Eclipse Adoptium hosts! check the readme on how to add more
# (if its not obvious enough).
# Initial host names are "os-arch-index" within each stanza
#

hosts:

  - infrastructure:

      - azure:
          ubuntu2004-x64-1: {ip: 40.121.206.1, user: webmaster, description: jckservices.adoptium.net}
          ubuntu2204-x64-1: {ip: 172.187.163.163, user: adoptopenjdk, description: infra-wazuh-server}
          ubuntu2204-x64-2: {ip: 20.90.182.165, description: trss.adoptium.net}
          ubuntu2204-x64-3: {ip: 172.187.93.97, description: awx.adoptium.net}

      - digitalocean:
          ubuntu2004-x64-1: {ip: 178.62.115.224, description: bastillion.adoptopenjdk.net}

      - hetzner:
          ubuntu1604-x64-1: {ip: 78.47.239.96, description: nagios.adoptopenjdk.net}
          ubuntu2004-x64-1: {ip: 78.47.239.97, description: ci.adoptium.net}

      - ibmcloud:
          vagrant-x64-1: {ip: 150.239.60.120, description: Bare metal machine to run vagrantPlaybookCheck and qemuPlaybookCheck}

      - osuosl:
          ubuntu2204-aarch64-1: {ip: 140.211.169.21, description: jenkins-worker}

  - build:

      - alibaba:
          win2012r2-x64-1: {ip: 8.208.11.212, user: Administrator}
          win2012r2-x64-2: {ip: 8.208.87.18, user: Administrator}
          ubuntu1804-armv8-1: {ip: 119.8.164.219}
          ubuntu1804-armv8-2: {ip: 159.138.100.163}

      - azure:
          win2022-x64-1: {ip: 172.187.129.163, user: adoptopenjdk}
          win2022-x64-2: {ip: 172.187.176.15, user: adoptopenjdk}
          win2022-x64-3: {ip: 51.142.8.47, user: adoptopenjdk}

      - digitalocean:
          centos69-x64-2: {ip: 167.71.130.191}

      - marist:
          rhel79-s390x-1: {ip: 148.100.75.212, user: linux1}
          rhel8-s390x-1: {ip: 148.100.75.98, user: linux1}

      - osuosl:
          aix72-ppc64-1: {ip: 140.211.9.166, description: p8-java1-adopt10.osuosl.org, 7200-02-04-1914}
          aix72-ppc64-2: {ip: 140.211.9.12, description: p8-aix1-adopt02.osuosl.org, 7200-02-04-1914}
          aix72-ppc64-3: {ip: 140.211.9.163, description: p8-java1-adopt09.osuosl.org, 7200-05-03-2135}
          centos74-ppc64le-1: {ip: 140.211.168.138}
          centos74-ppc64le-2: {ip: 140.211.168.117}
          ubuntu2204-aarch64-1: {ip: 140.211.169.57}


      - siteox:
          solaris10u11-sparcv9-1: {ip: cloud.siteox.com, port: 24322}

      - ibmcloud:
          win2022-x64-1: {ip: 52.118.206.11, user: Administrator}

  - docker:

      - skytap:
          ubuntu2004-ppc64le-1: {ip: 20.61.136.212}

  - dockerhost:

      - azure:
          ubuntu2204-x64-1: {ip: 52.180.147.157, description: Xeon Platinum 8272CL, 16 cores, 64GB}

      - equinix:
          ubuntu2404-armv8-1: {ip: 147.75.35.203, description: Ampere Altra 160 core, 512Gb}
          ubuntu2204-armv8-1: {ip: 139.178.86.243, description: Ampere Altra 160 cores, 512Gb}

      - osuosl:
          ubuntu2404-ppc64le-1: {ip: 140.211.168.214}
          ubuntu2404-aarch64-1: {ip: 140.211.167.67}

      - marist:
          ubuntu2404-s390x-1: {ip: 148.100.74.237, user: linux1}

      - skytap:
          ubuntu2004-ppc64le-1: {ip: 20.61.136.212, description: 32CPU, 400G}
          ubuntu2204-x64-1: {ip: 20.61.136.254, description: 24 core Intel X5650}

  - test:

      - alibaba:
          ubuntu1804-armv8-1: {ip: 119.8.166.104}
          ubuntu1804-armv8-2: {ip: 114.119.175.125}

      - azure:
          ubuntu2404-x64-1: {ip: 20.115.98.159, user: azureuser}
          win2016-x64-1: {ip: 172.172.147.29, user: adoptopenjdk}
          win2019-x64-1: {ip: 13.92.177.186, user: adoptopenjdk}
          win2022-x64-1: {ip: 51.132.234.42, user: adoptopenjdk}
          win2022-x64-2: {ip: 20.26.116.218, user: adoptopenjdk}
          win2022-x64-3: {ip: 20.68.165.213, user: adoptopenjdk}
          win2022-x64-4: {ip: 20.77.112.43, user: adoptopenjdk}
          win11-aarch64-1: {ip: 20.4.31.184, user: adoptopenjdk}
          win11-aarch64-2: {ip: 108.143.205.79, user: adoptopenjdk}

      - aws:
          rhel76-armv8-1: {ip: 18.202.36.216, user: ec2-user}
          rhel8-x64-1: {ip: 54.246.216.49}

      - osuosl:
          aix72-ppc64-1: {ip: 140.211.9.28, description: p8-aix1-adopt03.osuosl.org, 7200-04-02-2028}
          aix72-ppc64-2: {ip: 140.211.9.36, description: p8-aix1-adopt04.osuosl.org, 7200-02-05-1938}
          aix72-ppc64-3: {ip: 140.211.9.168, description: p8-java1-adopt07.osuosl.org, 7200-02-04-1914}
          aix72-ppc64-4: {ip: 140.211.9.169, description: p8-java1-adopt08.osuosl.org, 7200-02-04-1914}
          aix72-ppc64-5: {ip: 140.211.9.99, description: p9-aix1-adopt05.osuosl.org, 7200-02-04-1914}
          aix72-ppc64-6: {ip: 140.211.9.100, description: p9-aix1-adopt06.osuosl.org, 7200-02-04-1914}
          aix73-ppc64-1: {ip: 140.211.9.10, description: p8-aix1-adopt01.osuosl.org, 7300-01-02-2320}
          centos74-ppc64le-1: {ip: 140.211.168.228, user: centos}
          centos74-ppc64le-2: {ip: 140.211.168.217, user: centos}
          ubuntu1604-ppc64le-1: {ip: 140.211.168.227, user: ubuntu}
          ubuntu1604-ppc64le-2: {ip: 140.211.168.190, user: ubuntu}
          ubuntu1804-ppc64le-1: {ip: 140.211.168.5, user: ubuntu}
          ubuntu1804-ppc64le-2: {ip: 140.211.168.8, user: ubuntu}
          ubuntu2004-ppc64le-1: {ip: 140.211.168.235, user: ubuntu}
          ubuntu2404-aarch64-1: {ip: 140.211.169.12, user: ubuntu}

      - macincloud:
          macos1201-x64-1: {ip: 216.39.74.137, user: admin, description: DXT437}
          macos1201-x64-2: {ip: 216.39.74.140, user: admin, description: DXT440}

      - macstadium:
          macos1014-x64-1: {ip: 207.254.29.43, user: administrator, description: G3B i7/4C/16G/250G}

      - marist:
          rhel7-s390x-2: {ip: 148.100.74.92}
          rhel8-s390x-2: {ip: 148.100.74.2}
          sles12-s390x-2: {ip: 148.100.74.193}
          sles15-s390x-2: {ip: 148.100.74.154, ansible_python_interpreter: /usr/bin/python3}
          ubuntu2404-s390x-1: {ip: 148.100.75.204}
          ubuntu2204-s390x-1: {ip: 148.100.74.105}

      # Rise machines are hosted in Scaleway
      - rise:
          ubuntu2404-riscv64-1: {ip: 62.210.163.198, user: ubuntu}
          ubuntu2404-riscv64-2: {ip: 62.210.163.196, user: ubuntu}
          ubuntu2404-riscv64-3: {ip: 62.210.163.99, user: ubuntu}
          ubuntu2404-riscv64-4: {ip: 62.210.163.103, user: ubuntu}
          ubuntu2404-riscv64-5: {ip: 62.210.163.45, user: ubuntu}
          ubuntu2404-riscv64-6: {ip: 62.210.163.135, user: ubuntu}
          ubuntu2404-riscv64-7: {ip: 62.210.163.137, user: ubuntu}
          ubuntu2404-riscv64-8: {ip: 62.210.163.38, user: ubuntu}
          ubuntu2404-riscv64-9: {ip: 62.210.163.36, user: ubuntu}

      - siteox:
          solaris10u11-sparcv9-1: {ip: cloud.siteox.com, port: 53322}

      - skytap:
          ubuntu2004-ppc64le-1: {ip: 20.61.136.210}

      - ibmcloud:
          rhel6-x64-1: {ip: 169.48.4.140}
          rhel7-x64-1: {ip: 169.48.4.136}
          ubuntu1604-x64-1: {ip: 169.48.4.141}
