---

#
# AdoptOpenJDK hosts! check the readme on how to add more
# (if its not obvious enough).
# Initial host names are "os-arch-index" within each stanza
#

hosts:

  - infrastructure:

      - aws:
          ubuntu1604-x64-1: {ip: 54.78.186.5, user: ubuntu, description: trss.adoptopenjdk.net}

      - digitalocean:
          ubuntu2004-x64-1: {ip: 178.62.115.224, description: bastillion.adoptopenjdk.net}

      - packet:
          ubuntu1604-x64-1: {ip: 147.75.80.219, description: ansible.adoptopenjdk.net}
          ubuntu2004-x64-1: {ip: 147.75.80.235, description: awx.adoptopenjdk.net}

      - ibmcloud:
          vagrant-x64-1: {ip: 150.239.60.120, description: Bare metal machine to run vagrantPlaybookCheck and qemuPlaybookCheck}

  - build:

      - alibaba:
          win2012r2-x64-1: {ip: 8.208.11.212, user: Administrator}
          win2012r2-x64-2: {ip: 8.208.87.18, user: Administrator}
          ubuntu1804-armv8-1: {ip: 119.8.164.219}

      - azure:
          win2012r2-x64-1: {ip: 51.132.23.101, user: adoptopenjdk}
          win2012r2-x64-2: {ip: 51.132.22.249, user: adoptopenjdk}
          win2016-x64-1: {ip: 51.104.239.17, user: adoptopenjdk}

      - digitalocean:
          centos69-x64-2: {ip: 167.71.130.191}

      - packet_esxi:
          solaris10u11-x64-1: {ip: 147.75.85.212}
          solaris10u11-x64-2: {ip: 147.75.85.213}

      - inspira:
          solaris10u11-sparcv9-1: {}
          solaris10u11-sparcv9-2: {}

      - macstadium:
          macos1014-x64-1: {ip: 208.83.1.170, user: Administrator}
          macos1014-x64-2: {ip: 207.254.28.76, user: Administrator}
          macos1014-x64-3: {ip: 207.254.71.202, user: Administrator}
          macos11-arm64-1: {ip: 207.254.31.15, user: Administrator}
          macos11-arm64-2: {ip: 207.254.31.16, user: Administrator}

      - marist:
          rhel77-s390x-1: {ip: 148.100.86.102, user: linux1}
          rhel77-s390x-2: {ip: 148.100.245.197, user: linux1}

      - osuosl:
          aix71-ppc64-1: {ip: 140.211.9.10, description: ojdk01}
          aix71-ppc64-2: {ip: 140.211.9.12, description: ojdk02}
          centos74-ppc64le-1: {ip: 140.211.168.138}
          centos74-ppc64le-2: {ip: 140.211.168.117}

      - packet:
          centos74-armv8-1: {ip: 147.75.196.30, description: ThunderX}
          ubuntu1804-armv8-1: {ip: 139.178.82.234, description: D05}

      - scaleway:
          ubuntu1604-armv7-1: {ip: 212.47.233.28}
          ubuntu1604-armv7-2: {ip: 212.47.246.7}
          ubuntu1604-x64-1: {ip: 51.15.46.107}

      - ibmcloud:
          win2012r2-x64-1: {ip: 169.48.4.138, user: Administrator}
          win2012r2-x64-2: {ip: 169.48.4.142, user: Administrator}

      - spearhead:
          freebsd12-x64-1: {ip: 185.131.222.224}

  - docker:

      - aws:
          ubuntu1604-x64-1: {ip: 34.253.28.27, user: ubuntu}

      - marist:
          ubuntu1604-s390x-1: {ip: 148.100.113.58, user: ubuntu}

      - packet:
          ubuntu1604-armv8-1: {ip: 147.75.77.146, description: D05}
          ubuntu2004-armv8-1: {ip: 139.178.82.146, description: Ampere eMag}
          ubuntu2004-x64-1: {ip: 139.178.85.251, description: AMD EPYC}

      - scaleway:
          ubuntu1604-armv7-1: {ip: 51.158.73.136}

  - test:

      - alibaba:
          ubuntu1804-armv8-1: {ip: 119.8.166.104}

      - azure:
          win2012r2-x64-1: {ip: 13.68.134.204, user: adoptopenjdk}
          win2012r2-x64-3: {ip: 13.68.219.237, user: adoptopenjdk}
          win2016-x64-1: {ip: 52.149.211.210, user: adoptopenjdk}
          win2019-x64-1: {ip: 20.185.182.137, user: adoptopenjdk}

      - aws:
          rhel76-armv8-1: {ip: 18.202.36.216, user: ec2-user}
          rhel8-x64-1: {ip: 54.246.216.49}
          ubuntu1804-armv8-1: {ip: 34.243.202.254}
          win2019-x64-1: {ip: 34.244.74.139, user: Administrator}

      - gdams:
          debian10-riscv64-1: {ip: gdams.ddns.net}
          debian10-riscv64-2: {ip: gdams.ddns.net, port: 2222}

      - ibm:
          aix71-ppc64-1: {ip: 129.33.196.209, user: b9s010a}
          aix71-ppc64-2: {ip: 129.33.196.210, user: b9s010a}

      - inspira:
          solaris10u11-sparcv9-1: {}

      - osuosl:
          aix71-ppc64-1: {ip: 140.211.9.99, description: ojdk05}
          aix72-ppc64-1: {ip: 140.211.9.28, description: p8-aix2-ojdk03.osuosl.org}
          aix72-ppc64-2: {ip: 140.211.9.36, description: p8-aix2-ojdk04.osuosl.org}
          centos74-ppc64le-1: {ip: 140.211.168.228, user: centos}
          centos74-ppc64le-2: {ip: 140.211.168.217, user: centos}
          centos74-ppc64le-4: {ip: 140.211.168.245, user: centos}
          ubuntu1604-ppc64le-1: {ip: 140.211.168.227, user: ubuntu}
          ubuntu1604-ppc64le-2: {ip: 140.211.168.190, user: ubuntu}
          ubuntu1604-ppc64le-3: {ip: 140.211.168.248, user: ubuntu}
          ubuntu1604-ppc64le-4: {ip: 140.211.168.239, user: ubuntu}
          ubuntu1804-ppc64le-1: {ip: 140.211.168.5, user: ubuntu}
          ubuntu1804-ppc64le-2: {ip: 140.211.168.8, user: ubuntu}

      - packet:
          ubuntu1604-armv8-1: {ip: 147.75.74.50, description: ThunderX}
          ubuntu1604-armv8-2: {ip: 147.75.193.234, description: ThunderX}
          ubuntu1604-x64-1: {ip: 147.75.204.239}
          ubuntu1604-x64-2: {ip: 147.75.100.127}
          ubuntu1604-x64-3: {ip: 147.75.83.133}
          win2012r2-x64-1: {ip: 147.75.32.146, user: Admin}

      - macincloud:
          macos1010-x64-1: {ip: 74.80.250.151, user: admin, description: TBD}
          macos1010-x64-2: {ip: 74.80.250.173, user: admin, description: TBD}

      - macstadium:
          macos1012-x64-1: {ip: 208.83.1.46, user: administrator}
          macos1013-x64-1: {ip: 208.83.1.19, user: administrator}
          macos1014-x64-1: {ip: 207.254.29.43, user: administrator}
          macos1014-x64-2: {ip: 207.254.29.44, user: administrator}
          macos1014-x64-3: {ip: 207.254.28.237, user: administrator}
          macos1015-x64-1: {ip: 207.254.28.171, user: administrator}
          macos11-arm64-1: {ip: 199.7.163.51, user: Administrator}
          macos11-arm64-2: {ip: 199.7.163.52, user: Administrator}

      - marist:
          sles12-s390x-1: {ip: 148.100.86.128}
          ubuntu1604-s390x-1: {ip: 148.100.113.20, user: ubuntu}
          ubuntu1604-s390x-2: {ip: 148.100.113.25, user: ubuntu}
          ubuntu1604-s390x-3: {ip: 148.100.113.30, user: ubuntu}
          ubuntu1604-s390x-4: {ip: 148.100.113.46, user: ubuntu}


      # Nine machines are behind a firewall. Please contact @sxa or @gdams for access
      - nine:
          macos1015-x64-1: {ip: 10.0.40.10, ipv6: "2a02:418:3001:40::10", user: administrator}
          macos1015-x64-2: {ip: 10.0.40.11, ipv6: "2a02:418:3001:40::11", user: administrator}

      - scaleway:
          ubuntu1604-x64-1: {ip: 51.15.76.107}

      - ibmcloud:
          rhel6-x64-1: {ip: 169.48.4.140}
          rhel7-x64-1: {ip: 169.48.4.136}
          ubuntu1604-x64-1: {ip: 169.48.4.141}
          win2012r2-x64-1: {ip: 169.48.4.131, user: Administrator}
          win2012r2-x64-2: {ip: 169.48.4.139, user: Administrator}
