---

#
# AdoptOpenJDK hosts! check the readme on how to add more
# (if its not obvious enough).
# Initial host names are "os-arch-index" within each stanza
#

hosts:

  - infrastructure:

      - digitalocean:
          ubuntu1604-x64-1: {ip: 138.68.167.199, description: api.adoptopenjdk.net}

      - packet:
          ubuntu1604-x64-1: {ip: 147.75.80.219, description: ansible.adoptopenjdk.net}

      - softlayer:
          ubuntu1604-x64-3: {ip: 158.176.72.83, description: jckservices.adoptopenjdk.net}

      - godaddy:
          ubuntu1604-x64-1: {ip: 160.153.247.225, description: git-hg/load relief for jenkins master}

  - build:

      - azure:
          win2008r2-x64-1: {ip: 13.90.22.129, user: adoptopenjdk}
          win2008r2-x64-2: {ip: 13.82.55.70, user: adoptopenjdk}

      - digitalocean:
          centos69-x64-1: {ip: 159.65.95.239}
          centos69-x64-2: {ip: 167.71.130.191}

      - linaro:
          centos74-armv8-1: {ip: 64.28.99.122}
          centos74-armv8-2: {ip: 64.28.99.122, port: 2222}

      - macstadium:
          macos1010-x64-1: {ip: 207.254.50.138, user: Administrator}
          macos1010-x64-2: {ip: 208.83.1.242, user: Administrator}

      - marist:
          rhel74-s390x-1: {ip: 148.100.110.129}
          rhel74-s390x-2: {ip: 148.100.110.131}
          ubuntu1604-s390x-2: {ip: 148.100.33.178}
          ubuntu1604-s390x-3: {ip: 148.100.33.179}
          zos21-s390x-1: {ip: 148.100.36.136, user: OPEN1}
          zos21-s390x-2: {ip: 148.100.36.137, user: OPEN1}

      - osuosl:
          centos74-ppc64le-1: {ip: 140.211.168.138}
          centos74-ppc64le-2: {ip: 140.211.168.117}
          ubuntu1604-ppc64le-1: {ip: 140.211.168.243}
          aix71-ppc64-1: {ip: 140.211.9.10}
          aix71-ppc64-2: {ip: 140.211.9.12}

      - packet:
          centos74-armv8-1: {ip: 147.75.196.30}
          ubuntu1604-armv8-2: {ip: 147.75.77.146}

      - scaleway:
          ubuntu1604-x64-2: {ip: 51.15.46.107}
          ubuntu1604-armv7-1: {ip: 212.47.233.28}
          ubuntu1604-armv7-2: {ip: 212.47.246.7}

      - softlayer:
          win2012r2-x64-1: {ip: 37.58.103.195, user: Administrator}
          win2012r2-x64-2: {ip: 37.58.103.196, user: Administrator}

  - test:

      - azure:
          win2012r2-x64-1: {ip: 13.68.134.204, user: adoptopenjdk}
          win2012r2-x64-2: {ip: 40.121.164.56, user: adoptopenjdk}
          win2012r2-x64-3: {ip: 13.68.219.237, user: adoptopenjdk}

      - godaddy:
          win2016-x64-1: {ip: 160.153.234.27, user: adoptopenjdk}
          win2016-x64-2: {ip: 160.153.234.5, user: adoptopenjdk}
          win2016-x64-3: {ip: 160.153.234.8, user: adoptopenjdk}
          win2016-x64-4: {ip: 160.153.234.22, user: adoptopenjdk}
          debian8-x64-1: {ip: 160.153.246.223, user: adoptopenjdk}
          debian8-x64-2: {ip: 160.153.246.42, user: adoptopenjdk}
          debian8-x64-3: {ip: 160.153.246.234, user: adoptopenjdk}
          debian8-x64-4: {ip: 160.153.246.220, user: adoptopenjdk}
          ubuntu1604-x64-1: {ip: 160.153.245.145, user: adoptopenjdk}
          ubuntu1604-x64-2: {ip: 160.153.246.176, user: adoptopenjdk}
          ubuntu1604-x64-3: {ip: 160.153.246.222, user: adoptopenjdk}
          ubuntu1604-x64-4: {ip: 160.153.246.214, user: adoptopenjdk}
          centos7-x64-1: {ip: 160.153.244.82, user: adoptopenjdk}
          centos7-x64-2: {ip: 160.153.246.204, user: adoptopenjdk}
          centos7-x64-3: {ip: 160.153.246.194, user: adoptopenjdk}
          centos7-x64-4: {ip: 160.153.244.42, user: adoptopenjdk}

      - osuosl:
          ubuntu1604-ppc64le-1: {ip: 140.211.168.227, user: ubuntu}
          ubuntu1604-ppc64le-2: {ip: 140.211.168.190, user: ubuntu}

      - packet:
          ubuntu1604-armv8-1: {ip: 147.75.74.50}
          ubuntu1604-x64-1: {ip: 147.75.204.239}
          ubuntu1604-x64-2: {ip: 147.75.100.127}
          ubuntu1604-x64-3: {ip: 147.75.83.133}
          win2012r2-x64-1: {ip: 147.75.32.146, user: Admin}

      - macincloud:
          macos1010-x64-1: {ip: 74.80.250.151, user: admin}
          macos1010-x64-2: {ip: 74.80.250.173, user: admin}
          macos1012-x64-1: {ip: 92.63.141.139, user: admin}
          macos1013-x64-1: {ip: 46.20.235.28, user: admin}
          macos1013-x64-2: {ip: 92.63.134.23, user: admin}
          macos1014-x64-1: {ip: 87.237.62.57, user: admin}
          macos1014-x64-2: {ip: 92.63.134.40, user: admin}
          macos1014-x64-3: {ip: 74.80.249.207, user: admin}

      - marist:
          sles12-s390x-1: {ip: 148.100.110.56}
          ubuntu1604-s390x-1: {ip: 148.100.33.147}

      - scaleway:
          ubuntu1604-x64-1: {ip: 51.15.76.107}

      - softlayer:
          ubuntu1604-x64-1: {ip: 169.55.150.155}
          rhel74-x64-1: {ip: 169.55.170.70}
          rhel69-x64-1: {ip: 169.55.150.147}
          win2012r2-x64-1: {ip: 169.55.170.72, user: admin}

  - jck:

      - macstadium:
          macos1010-x64-1: {ip: 207.254.71.30, user: Administrator}
          macos1010-x64-2: {ip: 207.254.71.31, user: Administrator}

      - marist:
          ubuntu1604-s390x-1: {ip: 148.100.33.183, user: linux1}
          ubuntu1604-s390x-2: {ip: 148.100.33.184, user: linux1}

      - osuosl:
          ubuntu1604-ppc64le-1: {ip: 140.211.168.225, user: ubuntu}
          ubuntu1604-ppc64le-2: {ip: 140.211.168.217, user: ubuntu}

      - packet:
          ubuntu1604-armv8-1: {ip: 147.75.193.234}

      - joyent:
          win2012r2-x64-1: {ip: 165.225.150.83, user: Administrator}

      - softlayer:
          ubuntu1604-x64-1: {ip: 159.122.210.205}
          ubuntu1604-x64-2: {ip: 159.122.210.194}
          win2012r2-x64-1: {ip: 169.55.170.68, user: Administrator}
