###################
# IBM XL C 16.1.0 #
###################
---
- name: Checking for xlC16 installed as 'licensed' LPP
  stat:
    path: /usr/lpp/xlCcmp.16.1.0.license
  register: xlc16
  tags: xlc16

- name: Vendor File processing
  when: xlc16.stat.isdir is undefined
  tags: [xlc16, vendor_files]
  block:
    - name: Transfer and Extract XLC16
      unarchive:
        src: /Vendor_Files/aix/XLC/XL_C_Cpp_FOR_AIX_V16.1_EMG.tar.Z
        dest: /tmp
        remote_src: false
      register: _vendor_copied
      failed_when: false

    - name: Install IBM XLC16 - installp
      command: installp -aXYg -e /tmp/xlc16_install.log -d /tmp/usr/sys/inst.images all
      register: _installp
      failed_when: false
      when: _vendor_copied.failed is defined and _vendor_copied.failed == false

    - name: 'Errors from the previous installp command can be ignored'
      debug: msg='Errors from the previous installp command can be ignored'
      when: xlc16.stat.islnk is not defined
      tags: xlc16

    - name: Clean XLC16 tmp files
      file:
        path: /tmp/usr
        state: absent

- name: Query xlC version
  command: /opt/IBM/xlC/16.1.0/bin/xlc -qversion
  register: xlc16_qversion
  failed_when: false
  changed_when: false
  tags: xlc16

- name: Display XLC16 qversion information
  debug:
    msg: "{{ xlc16_qversion.stdout }}"
  when: xlc16_qversion.failed == false
  tags: xlc16

- name: Display error message
  debug:
    msg: "{{ xlc16_qversion.cmd }} returns {{ xlc16_qversion.msg }}"
  when: xlc16_qversion.failed == true
  tags: xlc16
