---
####################################################################
# AdoptOpenJDK - Ansible Playbook to install Nagios plugins on AIX #
####################################################################

###########################################################################
# License Information:                                                    #
# Nagios core and its plugins are lincesed under GPL                      #
# For more information please see: https://www.nagios.com/legal/licenses/ #
###########################################################################

- debug: msg='Installing Nagios plugins'
##########
# Layout #
##########
- name: Creates Nagios folder
  file: path=/usr/local/nagios/ state=directory mode=0755

- name: Creates Nagios libexec folder
  file: path=/usr/local/nagios/libexec/ state=directory mode=0755

##################
# Install Nagios #
##################
- name: Transfer over Nagios Plugins
  copy:
    src: "{{ item }}"
    dest: /usr/local/nagios/libexec/
    mode: 0755
  with_fileglob:
    - /Vendor_Files/aix/nagios/*
    # above path was /home/ubuntu/aix/nagios/*

###############
# Nagios user #
###############
- name: Setup Nagios user
  command: mkuser home="/home/nagios" shell="/usr/bin/ksh" nagios
  ignore_errors: yes
  tags:
    # TODO: write a condition when NOT to run this step
    - skip_ansible_lint

- name: Create SSH Key folder for Nagios
  file:
    path: /home/nagios/.ssh
    owner: nagios
    group: staff
    mode: 0700
    state: directory

- name: Setup authorized_keys
  file:
    path: /home/nagios/.ssh/authorized_keys
    owner: nagios
    group: staff
    mode: 0600
    state: touch

- name: Add key
  authorized_key:
    user: nagios
    state: present
    key: "{{ lookup('file', '{{ Nagios_User_SSHKey }}') }}"
