---
##########
# CentOS #
##########

# Command Build Tool Packages
Build_Tool_Packages:
  - alsa-lib-devel
  - autoconf
  - bind-utils
  - bison
  - bzip2
  - cpio
  - cups-devel
  - elfutils-libelf-devel
  - flex
  - fontconfig-devel
  - freetype-devel
  - gcc
  - gcc-c++
  - gettext
  - git
  - glibc
  - glibc-common
  - glibc-devel
  - gmp-devel
  - java-1.7.0-openjdk-devel
  - java-1.8.0-openjdk-devel
  - libdwarf-devel
  - libstdc++-static
  - libXext-devel
  - libXrender-devel
  - libXt-devel
  - libXtst-devel
  - lbzip2
  - make
  - mesa-libGL-devel
  - mpfr-devel
  - numactl-devel
  - ntp
  - openssl-devel
  - perl-CPAN
  - perl-DBI
  - perl-devel
  - perl-GD
  - perl-libwww-perl
  - perl-Time-HiRes
  - unzip
  - wget
  - xz
  - zip

gcc48_devtoolset_compiler:
  - devtoolset-2-gcc
  - devtoolset-2-binutils
  - devtoolset-2-gcc-c++

gcc73_devtoolset_compiler:
  - devtoolset-7-gcc
  - devtoolset-7-binutils
  - devtoolset-7-gcc-c++

Additional_Build_Tools_x86_64:
  - zulu-9

Test_Tool_Packages:
  - ant
  - mercurial
  - perl
  - xorg-x11-xauth
  - xorg-x11-server-Xorg
  - xorg-x11-server-Xvfb

crontab_Patching: "/usr/bin/yum -y update"
