---
##########
# CentOS #
##########

# Command Build Tool Packages
Build_Tool_Packages:
  - alsa-lib-devel
  - autoconf
  - bind-utils
  - bison                         # OpenJ9
  - bzip2
  - ca-certificates
  - cpio
  - curl
  - cups-devel
  - diffutils
  - elfutils-libelf-devel
  - file
  - flex                          # OpenJ9
  - fontconfig-devel
  - freetype-devel
  - gcc
  - gcc-c++
  - gettext
  - glibc
  - glibc-common
  - glibc-devel
  - gmp-devel
  - gnutls
  - gnutls-utils
  - java-1.8.0-openjdk-devel
  - libcurl-devel
  - libpng-devel
  - libXext-devel
  - libXi-devel                   # JDK12+ compilation
  - libXrandr-devel               # JDK12+ compilations
  - libXrender-devel
  - libXt-devel
  - libXtst-devel
  - make
  - mesa-libGL-devel
  - mpfr-devel
  - nss-devel
  - nss-tools
  - numactl-devel                 # OpenJ9
  - openssh-clients               # IBM: cloning over SSH
  - openssl-devel
  - patch                         # For DevKit creation that runs "patch"
  - perl-DBI
  - perl-devel
  - perl-Digest-SHA
  - perl-GD
  - perl-IPC-Cmd                  # required for openssl v3 compiles
  - perl-libwww-perl
  - perl-Time-HiRes
  - pigz
  - strace                        # For SBOM dependency analysis
  - systemtap-sdt-devel
  - texinfo                       # For DevKit creation (binutils build)
  - unzip
  - wget
  - which
  - xz
  - zip

gcc48_devtoolset_compiler:
  - devtoolset-2-gcc
  - devtoolset-2-binutils
  - devtoolset-2-gcc-c++

Additional_Build_Tools_CentOS7:
  - libstdc++-static
  - ccache
  - procps-ng

Additional_Build_Tools_CentOS8_CentOS9Stream:
  - glibc-locale-source
  - glibc-langpack-ja             # required for creating Japanese locales
  - glibc-langpack-ko             # required for creating Korean locales
  - glibc-langpack-zh             # required for creating Chinese locales
  - git
  - cmake
  - ccache
  - procps-ng

Additional_Build_Tools_NOT_CentOS8_CentOS9Stream:
  - lbzip2
  - java-1.7.0-openjdk-devel
  - ntp

Additional_Build_Tools_CentOS_x86:
  - glibc.i686                    # a dependency required for executing a 32-bit C binary
  - glibc-devel.i686              # a dependency required for executing a 32-bit C binary
  - libstdc++.i686                # a dependency required for executing a 32-bit C binary
  - libnss3.so
  - libnssutil3.so

Additional_Build_Tools_CentOS8_Stream:
  - libdwarf
  - libmpc-devel

Additional_Build_Tools_NOT_CentOS8_Stream:
  - libdwarf-devel                # OpenJ9

Test_Tool_Packages:
  - gcc
  - gcc-c++
  - unzip
  - zlib-devel
  - perl-devel
  - libcurl-devel
  - openssl-devel
  - mercurial
  - perl
  - perl-Test-Simple
  - xorg-x11-xauth
  - xorg-x11-server-Xvfb
  - fakeroot
  - gnutls
  - gnutls-utils
  - shared-mime-info
  - nss-devel
  - nss-tools
