---
########
# SUSE #
########

# Command Build Tool Packages
Build_Tool_Packages:
  - alsa-devel
  - autoconf
  - bind-utils
  - bison                         # OpenJ9
  - cpio
  - curl
  - cups
  - cups-devel
  - flex
  - gcc
  - gcc-c++
  - glibc
  - glibc-devel
  - gnutls
  - libcurl-devel
  - libdw1
  - libdwarf-devel
  - libelf-devel
  - libelf0
  - libelf1
  - libnss3.so
  - libnuma-devel
  - libpng15-devel
  - libXext-devel
  - libXi-devel
  - libXrandr-devel
  - libXrender-devel
  - libXt-devel
  - libXtst-devel
  - make
  - mozilla-nss
  - ntp
  - numactl
  - pkg-config
  - strace                        # For SBOM dependency analysis
  - systemtap-sdt-devel
  - unzip
  - wget
  - zip
  - zlib-devel

Additional_Build_Tools_SUSE12:
  - git-core
  - libfreetype6
  - libXext6
  - libXi6                        # JDK12+ compilation
  - libXrandr2                    # JDK12+ compilation
  - libXrender1
  - libXt6
  - libXtst6
  - Mesa-libGL1

Additional_Build_Tools_SUSE_x86:
  - glibc-32bit                   # a dependency required for executing a 32-bit C binary
  - glibc-devel-32bit             # a dependency required for executing a 32-bit C binary

Test_Tool_Packages:
  - perl
  - pulseaudio
  - xorg-x11
  - xorg-x11-devel
  - glibc-locale                  # Internationalization tests
  - gnutls
  - libnss3.so
  - mozilla-nss
