---
###############
# OracleLinux #
###############

# Command Build Tool Packages
Build_Tool_Packages:
  - alsa-lib-devel
  - bind-utils
  - bison
  - bzip2
  - crontabs
  - cpanminus
  - cpio
  - cups-devel
  - elfutils-libelf-devel
  - flex
  - freetype-devel
  - gcc
  - gcc-c++
  - gettext
  - git
  - glibc
  - glibc-common
  - glibc-devel
  - gmp-devel
  - ibutils
  - java-1.8.0-openjdk-devel
  - libdwarf
  - libXext-devel
  - libXi-devel # JDK12+ compilation
  - libXrandr-devel # JDK12+ compilation
  - libXrender-devel
  - libXt-devel
  - libXtst-devel
  - make
  - mesa-libGL-devel
  - mpfr-devel
  - ntp
  - openssl-devel
  - perl-CPAN
  - perl-DBI
  - perl-devel
  - perl-GD
  - perl-libwww-perl
  - sudo
  - unzip
  - wget
  - zip

Test_Tool_Packages:
  - perl
  - xorg-x11-xauth
  - xorg-x11-server-Xorg
  - xorg-x11-server-Xvfb

crontab_Patching: "/usr/bin/yum -y update"
