---
########
# SLES #
########

# Command Build Tool Packages
Build_Tool_Packages:
  - bind-utils
  - bison                         # OpenJ9
  - cpio
  - curl
  - flex
  - gcc
  - gcc-c++
  - glibc
  - glibc-devel
  - libdw1
  - libelf0
  - libelf1
  - make
  - ntp
  - pkg-config
  - unzip
  - wget
  - zip

Additional_Build_Tools_SLES12:
  - java-1_8_0-openjdk
  - git
  - libfreetype6
  - libXext6
  - libXi6                        # JDK12+ compilation
  - libXrandr2                    # JDK12+ compilation
  - libXrender1
  - libXt6
  - libXtst6
  - Mesa-libGL1
  - perl-CPAN-Meta

Additional_Build_Tools_SLES11:
  - perl-Error
  - libwww-perl

Test_Tool_Packages:
  - perl
  - pulseaudio
  - xorg-x11
  - xorg-x11-server
  - xorg-x11-server-extra
  - glibc-locale                  # Internationalization tests

crontab_Patching: "/usr/bin/zypper refresh && /usr/bin/zypper -n up"
