---
###########
# Solaris #
###########

# Command Build Tool Packages
Build_Tool_Packages:
  - autoconf
  - binutils
  - coreutils
  - ccache
  - ggrep
  - jdk7
  - jdk8
  - openssh # needed to clone from GitHub via ssh - https://github.com/adoptium/infrastructure/pull/2220
  - pigz
  - git
  - sudo
  - nano
  - ntp
  - wget
  - curl
  - gmake
  - gnupg
  - gtar
  - xz
  - zip
  - tcl
  - python27

Additional_Build_Tools_x64:
  - freetype

Test_Tool_Packages:
  - perl
