---
###########
# Solaris #
###########

# Command Build Tool Packages
Build_Tool_Packages:
  - autoconf
  - binutils
  - coreutils
  - ccache
  - ggrep
  - jdk7
  - jdk8
  - pigz
  - git
  - sudo
  - nano
  - ntp
  - wget
  - curl
  - freetype
  - gmake
  - gtar
  - xz
  - zip

Test_Tool_Packages:
  - perl
