---
##########
# Ubuntu #
##########

# Command Build Tool Packages
Build_Tool_Packages:
  - apt-transport-https
  - autoconf
  - bison
  - build-essential
  - cpanminus
  - cpio
  - curl
  - flex
  - g++
  - gcc
  - gettext
  - libasound2-dev
  - libcups2-dev
  - libcurl4-openssl-dev
  - libdwarf-dev
  - libelf-dev
  - libexpat1-dev
  - libffi-dev
  - libfreetype6-dev
  - libfontconfig1-dev
  - libgmp3-dev
  - libmpfr4
  - libmpfr4-dbg
  - libmpfr-dev
  - libmpfr-doc
  - libwww-perl
  - libx11-dev
  - libxext-dev
  - libxrender-dev
  - libxt-dev
  - libxtst-dev
  - make
  - numactl
  - ntp
  - openjdk-7-jdk
  - openjdk-8-jdk
  - pigz
  - pkg-config
  - wget
  - zip

OpenJFX_Build_Tool_Packages:
  - gperf
  - libavcodec-dev
  - libavformat-dev
  - libgl1-mesa-dev
  - libgstreamer0.10-dev
  - libgstreamer-plugins-base0.10-dev
  - libgtk2.0-dev
  - libgtk-3-dev
  - libjpeg-dev
  - libpng-dev
  - libudev-dev
  - libxml2-dev
  - libxslt1-dev
  - libxxf86vm-dev

gcc_compiler:
  - g++-4.8
  - gcc-4.8

Additional_Build_Tools_x86_64:
  - zulu-9
  - libnuma-dev
  - gcc-7
  - g++-7

Additional_Build_Tools_ppc64le:
  - libnuma-dev
  - gcc-7
  - g++-7

Additional_Build_Tools_s390:
  - gcc-7
  - g++-7

Additional_Build_Tools_aarch64:
  - libpng-dev

Test_Tool_Packages:
  - acl
  - mercurial
  - perl
  - xauth
  - xorg
  - xvfb
  - binfmt-support
  - qemu-user-static

Test_Tool_Packages_x86_64:
  - pulseaudio

crontab_Patching: "/usr/bin/apt-get update && /usr/bin/apt-get -y upgrade"
