---
##########
# Ubuntu #
##########

# Command Build Tool Packages
Build_Tool_Packages:
  - apt-transport-https
  - autoconf
  - bison                         # OpenJ9
  - build-essential
  - ca-certificates
  - cpio
  - curl
  - flex                          # Openj9
  - g++
  - gcc
  - gettext
  - git
  - gnupg
  - gnutls-bin
  - libasound2-dev
  - libcapstone-dev
  - libcups2-dev
  - libcurl4-openssl-dev
  - libdwarf-dev                  # OpenJ9
  - libelf-dev
  - libexpat1-dev
  - libffi-dev
  - libfreetype6-dev
  - libfontconfig1-dev
  - libgmp3-dev
  - libmpfr-dev
  - libmpfr-doc
  - libnss3
  - libnss3-tools
  - libnss3-dev
  - libssl-dev
  - libwww-perl
  - libx11-dev
  - libxext-dev
  - libxi-dev                     # JDK12+ compilation
  - libxrandr-dev                 # JDK12+ compilation
  - libxrender-dev
  - libxt-dev
  - libxtst-dev
  - make
  - ntp
  - pigz
  - pkg-config
  - strace                        # For SBOM dependency analysis
  - systemtap-sdt-dev
  - wget
  - zip

OpenJFX_Build_Tool_Packages:
  - gperf
  - libavcodec-dev
  - libavformat-dev
  - libgl1-mesa-dev
  - libgtk2.0-dev
  - libgtk-3-dev
  - libjpeg-dev
  - libpng-dev
  - libudev-dev
  - libxml2-dev
  - libxslt1-dev
  - libxxf86vm-dev
  - ruby

Additional_Packages_Ubuntu16:
  - libgstreamer0.10-dev                # OpenJFX prereq
  - libgstreamer-plugins-base0.10-dev   # OpenJFX prereq
  - libmpfr4
  - libmpfr4-dbg

Additional_Packages_Ubuntu18:
  - libgstreamer1.0-dev                 # OpenJFX prereq
  - libgstreamer-plugins-base1.0-dev    # OpenJFX prereq

Additional_Build_Tools_x86:
  - libnuma-dev
  - numactl
  - gcc-multilib                        # a dependency required for executing a 32-bit C binary

Additional_Build_Tools_ppc64le:
  - libnuma-dev
  - numactl

Additional_Build_Tools_s390x:
  - numactl
  - libfreetype6-dev              # Needed by test state=installed

Additional_Build_Tools_aarch64:
  - libpng-dev

Additional_Build_Tools_not_riscv64:
  - openjdk-8-jdk

Additional_Build_Tools_riscv64:
  - gcc-10
  - g++-10
  - openjdk-11-jdk
  - libatomic1

Additional_Build_Tools_Ubuntu20:
  - cmake
  - ccache

Test_Tool_Packages:
  - acl
  - perl
  - xauth
  - xvfb
  - binfmt-support
  - qemu-user-static
  - unzip
  - libexpat1-dev
  - libcurl4-openssl-dev
  - fakeroot
  - jq                            # For parsing SBoM during reproducibility tests
  - gnutls-bin
  - libnss3
  - libnss3-tools
  - libnss3-dev

Test_Tool_Packages_x86_64:
  - pulseaudio
