name: Linter

on:
  pull_request:
    paths:
    - ansible/**
    - .ansible-lint
    branches:         
    - master
  push:
    paths:
    - ansible/**
    branches:         
    - master

permissions:
  contents: read

jobs:
  yamllint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: write  # for karancode/yamllint-github-action to post comments on PRs
    name: Yamllint
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: 'Yamllint'
      uses: karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2 # v3.0.0
      with:
        yamllint_comment: true
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ansible_lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Python 3.x
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install ansible ansible-lint

    - name: ansible_lint
      run: |
        # Ansible code static analysis
        ansible-lint

        cd ansible
        # Check that the inventory is valid
        ansible-inventory --host build-marist-rhel79-s390x-1

        # Check Playbook syntax.
        ansible-playbook playbooks/AdoptOpenJDK_Unix_Playbook/main.yml --syntax-check
        ansible-playbook playbooks/AdoptOpenJDK_Unix_Playbook/trss.yml --syntax-check
        ansible-playbook playbooks/AdoptOpenJDK_AIX_Playbook/main.yml --syntax-check
        ansible-playbook playbooks/AdoptOpenJDK_Windows_Playbook/main.yml --syntax-check
        ansible-playbook playbooks/AdoptOpenJDK_Unix_Playbook/ubuntu-jckservices.yml --syntax-check
        ansible-playbook playbooks/vagrant.yml --syntax-check
        ansible-playbook playbooks/ubuntu-jck.yml --syntax-check
