name: Linter

on:
  pull_request:
    paths:
    - ansible/**
    - .ansible-lint
    branches:         
    - master
  push:
    paths:
    - ansible/**
    branches:         
    - master

permissions:
  contents: read

jobs:
  yamllint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: write  # for karancode/yamllint-github-action to post comments on PRs
    name: Yamllint
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: 'Yamllint'
      uses: karancode/yamllint-github-action@fdef6bc189425ecc84cc4543b2674566c0827053 # v2.1.1
      with:
        yamllint_comment: true
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ansible_lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: Set up Python 3.x
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install ansible ansible-lint

    - name: ansible_lint
      run: |
        # Ansible code static analysis
        ansible-lint

        cd ansible
        # Check that the inventory is valid
        ansible-inventory --host build-marist-rhel79-s390x-1

        # Check Playbook syntax.
        ansible-playbook playbooks/AdoptOpenJDK_Unix_Playbook/main.yml --syntax-check
        ansible-playbook playbooks/AdoptOpenJDK_Unix_Playbook/trss.yml --syntax-check
        ansible-playbook playbooks/AdoptOpenJDK_AIX_Playbook/main.yml --syntax-check
        ansible-playbook playbooks/AdoptOpenJDK_Windows_Playbook/main.yml --syntax-check
        ansible-playbook playbooks/AdoptOpenJDK_Unix_Playbook/ubuntu-jckservices.yml --syntax-check
        ansible-playbook playbooks/vagrant.yml --syntax-check
        ansible-playbook playbooks/ubuntu-jck.yml --syntax-check
